Repository be15-fin-Nexus-SION/be15-fin-Nexus-SION-BE, pull requests merged in 2025-07, with the labels that each got.

#192 [feat] 프로젝트 상태 및 확정 여부에 따른 스쿼드 조회 기능 구현
  src/main/java/com/nexus/sion/feature/squad/query/controller/SquadQueryController.java
  src/main/java/com/nexus/sion/feature/squad/query/repository/SquadQueryRepository.java
  src/main/java/com/nexus/sion/feature/squad/query/service/SquadQueryService.java
  src/main/java/com/nexus/sion/feature/squad/query/service/SquadQueryServiceImpl.java
Labels: 💡 feat, v1, 🌿 BE

#202 fix: 고객사 삭제 예외 처리 추가
  src/main/java/com/nexus/sion/exception/ErrorCode.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ClientCompanyCommandServiceImpl.java
Labels: v1, 🌿 BE, 🎱 fix

#206 [fix] ClientCompany 엔티티의 update 코드 수정
  src/main/java/com/nexus/sion/feature/project/command/domain/aggregate/ClientCompany.java
Labels: v1, 🌿 BE, 🎱 fix

#196 [fix] 프로젝트 목록 기능 수정
  src/main/java/com/nexus/sion/feature/project/query/dto/response/ProjectListResponse.java
  src/main/java/com/nexus/sion/feature/project/query/repository/ProjectQueryRepository.java
  src/test/java/com/nexus/sion/feature/evaluation/command/application/ProjectEvaluationCommandIntergrationTest.java
  src/test/java/com/nexus/sion/feature/evaluation/command/application/service/ProjectEvaluationCommandServiceImplTest.java
  src/test/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImplTest.java
Labels: v1, 🌿 BE, 🎱 fix

#210 [fix] 프로젝트 등록 기능 수정
  src/main/java/com/nexus/sion/common/s3/controller/DocumentS3Controller.java
  src/main/java/com/nexus/sion/common/s3/controller/ImageS3Controller.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/domain/aggregate/Project.java
Labels: v1, 🌿 BE, 🎱 fix

#214 [fix] 프로젝트 코드 자동생성
  src/main/java/com/nexus/sion/feature/project/command/application/dto/request/ProjectRegisterRequest.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/domain/repository/ProjectRepository.java
Labels: v1, 🌿 BE, 🎱 fix

#219 [feat] 개발자 목록 조회 api 등급, 역할별 필터 기능 구현
  src/main/java/com/nexus/sion/exception/ErrorCode.java
  src/main/java/com/nexus/sion/feature/member/query/dto/request/MemberListRequest.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryServiceImpl.java
Labels: 💡 feat, v2, 🌿 BE

#212 [Refactor] squad 관련 전체 리팩토링 및 기능 추가
  build.gradle
  logs/app-json.log
  src/main/java/com/nexus/sion/exception/ErrorCode.java
  src/main/java/com/nexus/sion/feature/member/query/controller/MemberQueryController.java
  src/main/java/com/nexus/sion/feature/member/query/dto/internal/MemberListQuery.java
  src/main/java/com/nexus/sion/feature/member/query/dto/request/MemberSquadSearchRequest.java
  src/main/java/com/nexus/sion/feature/member/query/dto/response/MemberSquadListResponse.java
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/util/MemberConditionBuilder.java
  src/main/java/com/nexus/sion/feature/member/query/util/SortFieldSelector.java
  src/main/java/com/nexus/sion/feature/project/command/application/controller/ProjectCommandController.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/domain/repository/ProjectAndJobRepository.java
  src/main/java/com/nexus/sion/feature/project/command/domain/repository/ProjectRepository.java
  src/main/java/com/nexus/sion/feature/project/query/controller/ProjectQueryController.java
  src/main/java/com/nexus/sion/feature/project/query/dto/response/JobRequirement.java
  src/main/java/com/nexus/sion/feature/project/query/dto/response/ProjectForSquadResponse.java
  src/main/java/com/nexus/sion/feature/project/query/mapper/ProjectQueryMapper.java
  src/main/java/com/nexus/sion/feature/project/query/service/ProjectQueryService.java
  src/main/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/command/application/controller/SquadCommandController.java
  src/main/java/com/nexus/sion/feature/squad/command/application/dto/internal/CandidateSummary.java
  src/main/java/com/nexus/sion/feature/squad/command/application/dto/internal/EvaluatedSquad.java
  src/main/java/com/nexus/sion/feature/squad/command/application/dto/internal/RequiredJobDto.java
  src/main/java/com/nexus/sion/feature/squad/command/application/dto/request/Developer.java
  src/main/java/com/nexus/sion/feature/squad/command/application/dto/request/SquadRegisterRequest.java
  src/main/java/com/nexus/sion/feature/squad/command/application/dto/request/SquadUpdateRequest.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommandService.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/command/domain/aggregate/entity/Squad.java
  src/main/java/com/nexus/sion/feature/squad/command/domain/service/SquadCodeGenerator.java
  src/main/java/com/nexus/sion/feature/squad/command/domain/service/SquadDomainService.java
  src/main/java/com/nexus/sion/feature/squad/command/domain/service/SquadEvaluatorImpl.java
  src/main/java/com/nexus/sion/feature/squad/command/domain/service/SquadGenerateEffortFP.java
  src/main/java/com/nexus/sion/feature/squad/command/domain/service/SquadValidationService.java
  src/main/java/com/nexus/sion/feature/squad/command/repository/SquadCommandRepository.java
  src/main/java/com/nexus/sion/feature/squad/query/controller/SquadQueryController.java
  src/main/java/com/nexus/sion/feature/squad/query/dto/response/AISquadDetailResponse.java
  src/main/java/com/nexus/sion/feature/squad/query/dto/response/DbDiagnosticInfo.java
  src/main/java/com/nexus/sion/feature/squad/query/dto/response/DeveloperSummary.java
  src/main/java/com/nexus/sion/feature/squad/query/dto/response/TestDto.java
  src/main/java/com/nexus/sion/feature/squad/query/mapper/SquadQueryMapper.java
  src/main/java/com/nexus/sion/feature/squad/query/repository/SquadQueryRepository.java
  src/main/java/com/nexus/sion/feature/squad/query/service/SquadQueryService.java
  src/main/java/com/nexus/sion/feature/squad/query/service/SquadQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/techstack/query/cotroller/TechStackQueryController.java
  src/main/java/com/nexus/sion/feature/techstack/query/repository/TechStackQueryRepository.java
  src/main/java/com/nexus/sion/feature/techstack/query/service/TechStackQueryService.java
  src/main/java/com/nexus/sion/feature/techstack/query/service/TechStackQueryServiceImpl.java
  src/main/resources/mappers/project/ProjectQueryMapper.xml
  src/main/resources/mappers/squad/SquadQueryMapper.xml
Labels: 💡 feat, v1, 🌿 BE

#222 [feat] 개발자 추가시 등급 산정 로직 추가
  src/main/java/com/nexus/sion/feature/member/command/application/service/MemberCommandService.java
  src/main/java/com/nexus/sion/feature/member/command/domain/aggregate/entity/Grade.java
  src/main/java/com/nexus/sion/feature/member/command/domain/repository/GradeRepository.java
Labels: 💡 feat, v2, 🌿 BE

#227 [Feat] 스쿼드 댓글 조회 기능 구현
  src/main/java/com/nexus/sion/feature/squad/command/application/controller/SquadCommandController.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommandService.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommentCommandService.java
  src/main/java/com/nexus/sion/feature/squad/command/domain/aggregate/entity/Squad.java
  src/main/java/com/nexus/sion/feature/squad/query/controller/SquadCommentQueryController.java
  src/main/java/com/nexus/sion/feature/squad/query/dto/response/SquadCommentResponse.java
  src/main/java/com/nexus/sion/feature/squad/query/repository/SquadCommentQueryRepository.java
  src/main/java/com/nexus/sion/feature/squad/query/service/SquadCommentQueryService.java
  src/main/java/com/nexus/sion/feature/squad/query/service/SquadCommentQueryServiceImpl.java
Labels: 💡 feat, v1, 🌿 BE

#223 프로젝트 수정 기능 수정
  src/main/java/com/nexus/sion/feature/project/command/application/controller/ProjectCommandController.java
  src/main/java/com/nexus/sion/feature/project/command/application/dto/request/ProjectUpdateRequest.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandService.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/test/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImplTest.java
Labels: v1, 🌿 BE, 🎱 fix

#242 Fix/241 project test code
  src/test/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImplTest.java
Labels: ⌛ test, v1, 🌿 BE

#266 [feat] 개발자 총 점수 조회 API 구현
  src/main/java/com/nexus/sion/feature/member/query/controller/FreelancerQueryController.java
  src/main/java/com/nexus/sion/feature/member/query/controller/MemberScoreQueryController.java
  src/main/java/com/nexus/sion/feature/member/query/dto/response/MemberScoreHistoryResponse.java
  src/main/java/com/nexus/sion/feature/member/query/repository/FreelancerQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberScoreQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberScoreHistoryQueryService.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberScoreHistoryQueryServiceImpl.java
Labels: 💡 feat, v2, 🌿 BE

#288 [Feat] 프리랜서 이력서 기반 점수 산정 로직 구현
  src/main/java/com/nexus/sion/common/fastapi/FastApiClient.java
  src/main/java/com/nexus/sion/exception/ErrorCode.java
  src/main/java/com/nexus/sion/feature/member/command/application/controller/FreelancerCommandController.java
  src/main/java/com/nexus/sion/feature/member/command/application/dto/response/FreelencerFpInferResponse.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/FreelancerCommandService.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/FreelancerCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/command/domain/aggregate/entity/DeveloperTechStackHistory.java
  src/main/java/com/nexus/sion/feature/project/command/application/dto/FunctionScore.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectEvaluateCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/query/dto/response/SquadDetailResponse.java
  src/main/java/com/nexus/sion/feature/squad/query/repository/SquadQueryRepository.java
  src/main/java/com/nexus/sion/feature/techstack/command/domain/aggregate/TechStack.java
  src/main/resources/application.yaml
Labels: v2, ☁️ FE, 🌿 BE

#297 [Test] 통합 테스트 코드 작성
  src/main/java/com/nexus/sion/feature/member/query/dto/request/MemberSquadSearchRequest.java
  src/main/java/com/nexus/sion/feature/project/command/application/dto/request/SquadReplacementRequest.java
  src/main/java/com/nexus/sion/feature/project/query/dto/request/ReplacementRecommendationRequest.java
  src/main/java/com/nexus/sion/feature/squad/command/application/controller/SquadCommandController.java
  src/main/java/com/nexus/sion/feature/squad/command/application/dto/request/SquadRecommendationRequest.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/query/util/JsonUtils.java
  src/test/java/com/nexus/sion/feature/member/query/MemberQueryIntegrationTest.java
  src/test/java/com/nexus/sion/feature/project/command/application/ProjectAnalyzeIntegrationTest.java
  src/test/java/com/nexus/sion/feature/project/command/application/ProjectCommandServiceIntegrationTest.java
  src/test/java/com/nexus/sion/feature/project/query/ProjectQueryIntegrationTest.java
  src/test/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImplTest.java
  src/test/java/com/nexus/sion/feature/squad/command/SquadCommandIntegrationTest.java
  src/test/java/com/nexus/sion/feature/squad/command/SquadCommentIntegrationTest.java
  src/test/java/com/nexus/sion/feature/squad/query/SquadQueryIntegrationTest.java
  src/test/java/com/nexus/sion/feature/techstack/query/TechStackQueryIntegrationTest.java
Labels: ⌛ test

#301 [fix] 개발자 검색 버그 해결
  src/main/java/com/nexus/sion/common/fastapi/FastApiClient.java
  src/main/java/com/nexus/sion/exception/ErrorCode.java
  src/main/java/com/nexus/sion/feature/member/command/application/controller/FreelancerCommandController.java
  src/main/java/com/nexus/sion/feature/member/command/application/dto/response/FreelencerFpInferResponse.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/FreelancerCommandService.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/FreelancerCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/query/dto/request/MemberListRequest.java
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/repository/UserCertificateHistoryQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/query/service/UserCertificateHistoryQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImpl.java
Labels: 🐜 bug, v2, 🌿 BE, 🎱 fix

#299 [feat] 개발자 교육추천 기능 구현
  src/main/java/com/nexus/sion/feature/member/command/domain/aggregate/entity/TrainingProgram.java
  src/main/java/com/nexus/sion/feature/member/command/domain/aggregate/entity/TrainingRecommendation.java
  src/main/java/com/nexus/sion/feature/member/query/controller/TrainingRecommendationQueryController.java
  src/main/java/com/nexus/sion/feature/member/query/dto/response/TrainingProgramResponse.java
  src/main/java/com/nexus/sion/feature/member/query/dto/response/TrainingRecommendationResponse.java
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberTechStackQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/repository/TrainingProgramQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/repository/UserCertificateHistoryQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/service/TrainingRecommendationQueryService.java
  src/main/java/com/nexus/sion/feature/member/query/service/TrainingRecommendationQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/query/service/UserCertificateHistoryQueryService.java
  src/main/java/com/nexus/sion/feature/member/query/service/UserCertificateHistoryQueryServiceImpl.java
  target/generated-sources/jooq/com/example/jooq/generated/Keys.java
  target/generated-sources/jooq/com/example/jooq/generated/enums/ProjectStatus.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/DeveloperProjectWork.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/DeveloperProjectWorkHistory.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/DeveloperProjectWorkHistoryTechStack.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/DeveloperTechStackHistory.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/MemberScoreHistory.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/Notification.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/Project.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/SquadEmployee.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/TrainingProgram.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/TrainingRecommendation.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/daos/TrainingProgramDao.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/daos/TrainingRecommendationDao.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/pojos/TrainingProgram.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/pojos/TrainingRecommendation.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/records/TrainingProgramRecord.java
  target/generated-sources/jooq/com/example/jooq/generated/tables/records/TrainingRecommendationRecord.java
Labels: 💡 feat, v2, 🌿 BE

#306 Feat/229 approve or reject project history
  src/main/java/com/nexus/sion/exception/ErrorCode.java
  src/main/java/com/nexus/sion/feature/notification/command/domain/aggregate/NotificationType.java
  src/main/java/com/nexus/sion/feature/project/command/application/controller/DeveloperProjectWorkCommandController.java
  src/main/java/com/nexus/sion/feature/project/command/application/controller/ProjectCommandController.java
  src/main/java/com/nexus/sion/feature/project/command/application/dto/request/SquadReplacementRequest.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/DeveloperProjectWorkService.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/DeveloperProjectWorkServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandService.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/domain/aggregate/DeveloperProjectWork.java
  src/main/java/com/nexus/sion/feature/project/query/controller/DeveloperProjectWorkQueryController.java
  src/main/java/com/nexus/sion/feature/project/query/controller/ProjectQueryController.java
  src/main/java/com/nexus/sion/feature/project/query/dto/request/ReplacementRecommendationRequest.java
  src/main/java/com/nexus/sion/feature/project/query/dto/request/WorkRequestQueryDto.java
  src/main/java/com/nexus/sion/feature/project/query/dto/response/WorkInfoQueryDto.java
  src/main/java/com/nexus/sion/feature/project/query/repository/DeveloperProjectWorkQueryRepository.java
  src/main/java/com/nexus/sion/feature/project/query/repository/ProjectQueryRepository.java
  src/main/java/com/nexus/sion/feature/project/query/repository/ReplacementRecommendationRepository.java
  src/main/java/com/nexus/sion/feature/project/query/service/DeveloperProjectWorkQueryService.java
  src/main/java/com/nexus/sion/feature/project/query/service/DeveloperProjectWorkQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/query/service/ReplacementRecommendationService.java
  src/main/java/com/nexus/sion/feature/project/query/service/ReplacementRecommendationServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/command/application/controller/SquadCommandController.java
  src/main/java/com/nexus/sion/feature/squad/command/repository/SquadEmployeeCommandRepository.java
  src/main/java/com/nexus/sion/feature/squad/query/util/CalculateSquad.java
  src/test/java/com/nexus/sion/feature/member/query/MemberQueryIntegrationTest.java
  src/test/java/com/nexus/sion/feature/project/command/application/ProjectAnalyzeIntegrationTest.java
  src/test/java/com/nexus/sion/feature/project/command/application/ProjectCommandServiceIntegrationTest.java
  src/test/java/com/nexus/sion/feature/project/query/ProjectQueryIntegrationTest.java
  src/test/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImplTest.java
  src/test/java/com/nexus/sion/feature/squad/command/SquadCommandIntegrationTest.java
  src/test/java/com/nexus/sion/feature/squad/command/SquadCommentIntegrationTest.java
  src/test/java/com/nexus/sion/feature/squad/query/SquadQueryIntegrationTest.java
  src/test/java/com/nexus/sion/feature/techstack/query/TechStackQueryIntegrationTest.java
Labels: 🐜 bug, 💡 feat, v2, 🌿 BE

#303 [Feat] 관리자 메인 대시보드 조회 기능 구현
  src/main/java/com/nexus/sion/feature/member/query/controller/MemberQueryController.java
  src/main/java/com/nexus/sion/feature/member/query/dto/response/DashboardSummaryResponse.java
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryService.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryServiceImpl.java
Labels: 💡 feat, v2, 🌿 BE

#305 월별 점수 조회 기능 구현
  src/main/java/com/nexus/sion/feature/member/query/controller/MemberQueryController.java
  src/main/java/com/nexus/sion/feature/member/query/dto/response/ScoreTrendDto.java
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryService.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryServiceImpl.java
Labels: 💡 feat, v2, 🌿 BE

#310 수정
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryServiceImpl.java
Labels: v1, v2, 🌿 BE, 🎱 fix

#304 [test] 단위 테스트 코드 수정
  src/main/java/com/nexus/sion/feature/member/command/application/controller/AdminCertificateController.java
  src/main/java/com/nexus/sion/feature/member/command/application/controller/CertificateCommandController.java
  src/main/java/com/nexus/sion/feature/member/command/application/controller/UserCertificateHistoryController.java
  src/main/java/com/nexus/sion/feature/member/command/application/dto/request/CertificateRejectRequest.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/AdminCertificateApprovalService.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/AdminCertificateApprovalServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/AdminCertificateCommandService.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/AdminCertificateCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/DeveloperCertificateHistoryService.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/DeveloperCertificateHistoryServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/UserCertificateHistoryService.java
  src/main/java/com/nexus/sion/feature/project/command/application/controller/ProjectCommandController.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommentCommandService.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommentCommandServiceImpl.java
  src/test/java/com/nexus/sion/feature/member/command/application/service/AdminCertificateApprovalServiceImplTest.java
  src/test/java/com/nexus/sion/feature/member/command/application/service/AdminCertificateCommandServiceImplTest.java
  src/test/java/com/nexus/sion/feature/member/command/application/service/DeveloperCertificateHistoryServiceImplTest.java
  src/test/java/com/nexus/sion/feature/member/query/service/CertificateQueryServiceImplTest.java
  src/test/java/com/nexus/sion/feature/member/query/service/TrainingRecommendationQueryServiceImplTest.java
  src/test/java/com/nexus/sion/feature/member/query/service/UserCertificateHistoryQueryServiceImplTest.java
  src/test/java/com/nexus/sion/feature/squad/command/application/service/SquadCommandServiceImplTest.java
  src/test/java/com/nexus/sion/feature/squad/command/application/service/SquadCommentCommandServiceTest.java
  src/test/java/com/nexus/sion/feature/squad/query/controller/SquadQueryControllerTest.java
  src/test/java/com/nexus/sion/feature/squad/query/service/SquadCommentQueryServiceImplTest.java
  src/test/java/com/nexus/sion/feature/squad/query/service/SquadQueryServiceImplTest.java
Labels: ⌛ test, v2, 🌿 BE

#317 [feat] default profile image 등록
  src/main/java/com/nexus/sion/feature/member/command/application/service/FreelancerCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/MemberCommandService.java
  src/main/java/com/nexus/sion/feature/member/command/domain/aggregate/entity/Member.java
Labels: 💡 feat, v2, 🌿 BE

#327 [chore] dockerfile 생성
  Dockerfile
Labels: 🥨 chore, 🌿 BE

#329 [chore] github workflow로 docker build, ECR push 자동화
  .github/workflows/deploy-backend.yml
Labels: 🥨 chore, 🌿 BE

#331 [chore] Update Dockerfile
  Dockerfile
Labels: 🥨 chore, 🌿 BE

#332 [chore] Update Dockerfile
  Dockerfile
Labels: 🥨 chore, 🌿 BE

#336 [feat] 프리랜서 등록시 등급 산정
  src/main/java/com/nexus/sion/feature/member/command/application/service/FreelancerCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/member/command/application/service/MemberCommandService.java
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryServiceImpl.java
Labels: 💡 feat, v2, 🌿 BE

#339 [Feat] 프로젝트 이력 승인 내역 조회 기능 구현 및 프로젝트 상태 수정 코드 리팩토링
  src/main/java/com/nexus/sion/common/s3/service/DocumentS3Service.java
  src/main/java/com/nexus/sion/exception/ErrorCode.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/repository/DeveloperProjectWorkRepository.java
  src/main/java/com/nexus/sion/feature/project/query/controller/DeveloperProjectWorkQueryController.java
  src/main/java/com/nexus/sion/feature/project/query/controller/ProjectQueryController.java
  src/main/java/com/nexus/sion/feature/project/query/dto/response/DeveloperApprovalResponse.java
  src/main/java/com/nexus/sion/feature/project/query/repository/DeveloperProjectWorkQueryRepository.java
  src/main/java/com/nexus/sion/feature/project/query/service/DeveloperProjectWorkQueryService.java
  src/main/java/com/nexus/sion/feature/project/query/service/DeveloperProjectWorkQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/command/repository/SquadEmployeeCommandRepository.java
Labels: 💡 feat, v2, 🌿 BE

#340 [Refactor] 관리자 메인 대시보드 조회 변경
  src/main/java/com/nexus/sion/feature/member/query/dto/response/DashboardSummaryResponse.java
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberQueryRepository.java
  src/main/java/com/nexus/sion/feature/member/query/service/MemberQueryServiceImpl.java
Labels: 🛁 refactor, v2, 🌿 BE

#344 [feat] 보유 자격증 조회 인가 로직 수정
  src/main/java/com/nexus/sion/feature/member/query/controller/UserCertificateHistoryQueryController.java
Labels: 🐜 bug, 🌿 BE, 🎱 fix

#347 수정
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
Labels: 🌿 BE, 🎱 fix

#348 [chore] docker build시 timezone 설정
  Dockerfile
Labels: 🐜 bug, 🥨 chore, 🌿 BE

#359 [chore] update workflow deploy-backend.yml
  .github/workflows/deploy-backend.yml
Labels: 🥨 chore, 🌿 BE

#361 argocd test
  Dockerfile
Labels: 🥨 chore, 🌿 BE

#365 [chore] argocd test
  Dockerfile
Labels: 🥨 chore, 🌿 BE

#367 [Refactor] fastapi 연결 api 변경
  src/main/java/com/nexus/sion/feature/member/command/application/service/FreelancerCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/application/dto/request/ProjectRegisterRequest.java
  src/main/resources/application.yaml
Labels: 🛁 refactor, v2, 🌿 BE

#368 fix: 배포시에 문제가 되는 SION 테이블명 삭제
  src/main/resources/mappers/squad/SquadQueryMapper.xml
Labels: 🐜 bug, 🌿 BE

#373 fix: 통계, 관리자 대시보드 조회 시 admin 포함 안 되게 수정
  src/main/java/com/nexus/sion/feature/member/query/repository/MemberQueryRepository.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/DeveloperProjectWorkCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/project/command/domain/aggregate/Project.java
  src/main/java/com/nexus/sion/feature/project/command/repository/DeveloperProjectWorkRepository.java
  src/main/java/com/nexus/sion/feature/project/query/controller/ProjectQueryController.java
  src/main/java/com/nexus/sion/feature/project/query/dto/request/MyProjectListRequest.java
  src/main/java/com/nexus/sion/feature/project/query/repository/DeveloperProjectWorkQueryRepository.java
  src/main/java/com/nexus/sion/feature/project/query/repository/ProjectQueryRepository.java
  src/main/java/com/nexus/sion/feature/project/query/service/DeveloperProjectWorkQueryService.java
  src/main/java/com/nexus/sion/feature/project/query/service/ProjectQueryServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/statistics/query/controller/StatisticsQueryController.java
  src/main/java/com/nexus/sion/feature/statistics/query/repository/StatisticsQueryRepository.java
  src/test/java/com/nexus/sion/feature/project/command/application/service/DeveloperProjectWorkCommandServiceImplTest.java
  src/test/java/com/nexus/sion/feature/project/query/service/DeveloperProjectWorkQueryServiceImplTest.java
Labels: 🛁 refactor, v2, 🌿 BE, 🎱 fix

#375 [fix] 프로젝트 종료일 반환하게 수정
  src/main/java/com/nexus/sion/feature/project/query/dto/response/ProjectDetailResponse.java
  src/main/java/com/nexus/sion/feature/project/query/repository/ProjectQueryRepository.java
Labels: v2, 🌿 BE, 🎱 fix

#387 Refactor/385 update notification message
  src/main/java/com/nexus/sion/feature/member/command/application/scheduler/MemberGradeScheduler.java
  src/main/java/com/nexus/sion/feature/notification/command/domain/aggregate/NotificationType.java
  src/main/java/com/nexus/sion/feature/project/command/application/service/ProjectEvaluateCommandServiceImpl.java
  src/main/java/com/nexus/sion/feature/squad/command/application/service/SquadCommandServiceImpl.java
Labels: 🛁 refactor, v2, 🌿 BE

#394 refactor: 커스텀 스쿼드 생성 -> ai 추천에서 추가를 했을 때 이미지 가져오기
  src/main/java/com/nexus/sion/feature/squad/query/dto/response/DeveloperSummary.java
  src/main/resources/mappers/squad/SquadQueryMapper.xml
Labels: v2, 🌿 BE, 🎱 fix

#395 refactor: 커스텀 스쿼드 생성 -> ai 추천에서 추가를 했을 때 이미지 가져오기
  src/main/resources/mappers/squad/SquadQueryMapper.xml
Labels: 🐜 bug, v2, 🌿 BE
